language: ruby
rvm:
  - 2.3.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: F6wCA9Gp7+vRRl/JzEqr2Lp0f/lGd+VnDVNX8ifOjQqOtCKvHNz5+9P+FaxCouDSicq5d1z7FdHGaGRsERDbo/oWfoDh81fNx/DaQoMaPC30xt4ihIP7d3AcPj15Y5WoqzNFejOCMFxkg2T0P8kiaj/0yQsiAXfiQmRC3jaemOaK2ashxj7MR7OXdPh0EwjZ4xKFiaFQVTau0vULqRAwe3IJ3XbrHsCl/mEimEPH3lse0/+ZnCbrmC6bRQf327gbOk53PWeagLH/mxXK188073Ju037d9w6b/5pkrfCSpTIaQ4Q0y7bhHp9CgmvU6xAzFW2QsglMUIefGKcpPeJ3RkA/iJH9dLGkTaVeRBwTleS4kAhQVHO/RdeTnJPAazm5KWX3WoTOo9Fd0B/ShJddHVEB2FpkVhNIQ3USxLMq8N8IExWLF99tLcIeM3kK1cMVW1wJMdEXe/v9ifzkrv3OCveKgfIuzULRFrlPxKSS9DLSQWtIFZKUFG6Doj4hw+679fNdfW3FvDUWgJNTjPskxMfxpsbn7IAqxx4dY2iLH4O1eHKoLIwsZ0KUZPr8O8HI6QM5YhtRJNPmukcAvdXtErl1w29YMorUmNDc/LM0gl1zjLEc8jt2/TTPsUNitzhqZiBZhMmFk9USrvpcTsik6HFw4vmfR4sCn4dygOV/P4k=
deploy:
  provider: rubygems
  api_key:
    secure: shl5iQVT11TYdOTEy9rXePLOukcInAIoYUdzeXEKwiszwxJ0XKC62DRBkXqIKf9goYyHnd96EQfYFBy9yjbtcwp/pJ9TUxOFBIIwr1OJduble8WduJgAgG3xIG7i7gUB7DnCDSC8jdKO28v03UzyvZw5zNFzzugzPy+H27BHcfp1KEoor31U0uMS/4qjfSAmS8mxejuPj5JmL8GKghMcGbLNOY8lqDLNfF5mCaYCBUrnFsqxlnbQsnymAsZKQXtdg3fUV6GHfV/YTOdA8rdmVUBaiQMV8JZZNE0PZG+neJ/3uIW+MHB8PZdz5Df5BwB/G1cw77A42pjO0UNTgImeDPXsGLkOmI5rl0hrxigLJ6GjV+Qur//kNlSusmbKIA6YMmnCd2NPVYt7BUejtS/kUIPBC9Lppq2BQTbkpXhy51a9e4kKH6zNw173XIHwLAj9c4+c/H5Pde7zfXNGp1pPQ17tk+Bk6G7Sosfb+ZBY0elmoZCNwr0DDi6icVujkg70CHTzEfzx/fI8ejZ/L0dVuB9kGZ9MZ3MWd38//Zp4jWzKD422nHdh1RlU7jR4M2rn9WKPW8l6mKJ9r1ozK/hyLqcQGKl/QqXNBc7oOL8rYLXszbmHqq99uE1+uw+oQP0e+SkX/F2w6gWHX4n9VY0hUMzz4y/QUG4iM3/1yIZtJgo=
  gem: device_wizard
  on:
    tags: true
    repo: Sage/device_wizard
    condition: "$TRAVIS_RUBY_VERSION == 2.3.5"
